// texts.js

const TEXTS = Object.freeze({
    title: '🌘 ЛУННАЯ ДОСТАВКА',
    subtitle: 'Симулятор логистики лунной базы',

    money: 'Кредиты',
    reputation: 'Рейтинг базы',
    sol: 'Сол',
    tick: 'Тик',

    roversTitle: '🤖 Роверы',
    ordersTitle: '📦 Заказы',
    eventsTitle: '📡 Журнал событий',
    legendTitle: '🗺 Зоны Луны',

    weight: 'Вес',
    kg: 'кг',
    battery: 'Батарея',
    capacity: 'Грузоподъёмность',
    reward: 'Награда',
    urgency: 'Срочность',
    risk: 'Риск маршрута',
    distance: 'Расстояние',
    cells: 'кл.',
    speed: 'Скорость',
    status: 'Статус',

    status_idle: 'Свободен',
    status_delivering: 'В доставке',
    status_charging: 'Заряжается',
    status_broken: 'Повреждён',

    order_pending: 'Ожидает',
    order_in_progress: 'В пути',
    order_delivered: 'Доставлен',
    order_expired: 'Просрочен',
    order_failed: 'Провален',

    deliver: '🚀 Доставить',
    charge: '⚡ Зарядить',
    repair: '🔧 Починить',
    buy: 'Купить',
    cancel: 'Отмена',
    newGame: '🔄 Новая игра',
    pause: '⏸ Пауза',
    resume: '▶ Продолжить',
    close: 'Закрыть',
    speedLabel: '⚡ Скорость: x',

    selectRover: 'Выберите ровера',
    selectOrder: 'Выберите заказ',
    notEnoughBattery: 'Не хватает заряда батареи',
    notEnoughCapacity: 'Заказ слишком тяжёлый для этого ровера',
    roverBusy: 'Ровер занят',
    roverBroken: 'Ровер повреждён — нужна починка',
    deliveryStarted: 'Доставка начата',
    deliverySuccess: '✅ Доставка успешна! +{reward} кредитов',
    deliveryFailed: '❌ Авария! Ровер повреждён, заказ провален',
    orderExpired: '⏰ Заказ просрочен! Рейтинг −{loss}',
    cannotAfford: 'Недостаточно кредитов',
    repaired: '🔧 Ровер починен',
    charging: '⚡ Ровер на зарядке',
    gameOver: '💀 РЕЙТИНГ БАЗЫ УТРАЧЕН',
    gameOverSub: 'Игра окончена. Заработано кредитов: {money}',
    victory: '🏆 ОТЛИЧНАЯ РАБОТА!',

    eventRoverBroke: '⚠ {rover} попал в завал и повреждён',
    eventDustStorm: '🌪 Пыльная буря замедлила {rover}',
    eventBonus: '💎 {rover} нашёл лунный кристалл! +{amount} кредитов',
    eventOrderSpawn: '📦 Новый заказ #{id} ({weight}кг, {reward}💰)',

    legendBase: 'База — безопасно',
    legendPlains: 'Равнины — быстрый путь',
    legendCraters: 'Кратеры — средний риск',
    legendMountains: 'Горы — высокий риск',
    legendDarkside: 'Тёмная сторона — экстремально',

    hintSelectOrder: 'Выберите заказ на карте или в списке',
    hintSelectRover: 'Выберите ровера для доставки',
    hintImpossible: 'Доставка невозможна: не хватает батареи/грузоподъёмности',
});